name: Trigger auto deployment for nftlend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nftlend-AutoDeployTrigger-fe6efea1-56e6-45ff-8745-ac389e278760.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NFTLEND_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.NFTLEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NFTLEND_REGISTRY_PASSWORD }}
          containerAppName: nftlend
          resourceGroup: containers
          imageToBuild: collasanta/nftlend:${{ github.sha }}
          
            

     

